name: deploy to ec2 with jar
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-branch
        uses: action/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: build jar
        working-directory: . # 현재 위치
        run: | # 명령어가 2줄 이상 되면 이렇게 써주기
          chmod 777 ./gradlew
          ./gradlew bootJar
      - name: copy jar to ec2
        uses: appleboy/scp-action@master
        with:
          host: ec2-13-209-18-179.ap-northeast-2.compute.amazonaws.com
          username: ubuntu # ec2 연결로 들어가보면 계정명이 ubuntu이기 때문이다.
          # pem 키를 통해 해당 인스턴스에 접근한다.
          key: ${{secrets.EC2_PEMKEY}}
          source: "./build/libs/*.jar" # 어떤 jar든지 간에 상관없음. 왜냐면 어차피 하나밖에 안만들어짐
          target: "/home/ubuntu"